/**
 * ASS subtitle generation — turns normalized transcript cues into a styled
 * .ass file that the export's burn stage overlays via ffmpeg's `ass` filter.
 * ASS (not SRT) is used because font/size/color/outline/position are all
 * first-class style fields the user can configure in the settings UI.
 *
 * PURE module.
 */

import type { SubtitleStyle } from "../export/plan";

export interface SubtitleCue {
  /** Cue window on the timeline being subtitled (the post-EDL output video). */
  startMs: number;
  endMs: number;
  text: string;
}

export const DEFAULT_SUBTITLE_STYLE: SubtitleStyle = {
  fontFamily: "Microsoft YaHei",
  fontSize: 28,
  color: "#FFFFFF",
  outlineColor: "#000000",
  outlineWidth: 2,
  position: "bottom",
  marginV: 40,
};

/** ASS colours are &HAABBGGRR (alpha, blue, green, red). */
export function toAssColor(hex: string, alpha = 0): string {
  const clean = (hex || "").replace("#", "").trim();
  const full = clean.length === 3
    ? clean.split("").map((c) => c + c).join("")
    : clean.padEnd(6, "0").slice(0, 6);
  const r = full.slice(0, 2);
  const g = full.slice(2, 4);
  const b = full.slice(4, 6);
  const a = Math.round(Math.max(0, Math.min(1, alpha)) * 255)
    .toString(16).padStart(2, "0");
  return `&H${a}${b}${g}${r}`.toUpperCase();
}

/** Centiseconds clock: H:MM:SS.CC */
export function assTime(ms: number): string {
  const total = Math.max(0, ms);
  const cs = Math.floor((total % 1000) / 10);
  const s = Math.floor(total / 1000) % 60;
  const m = Math.floor(total / 60000) % 60;
  const h = Math.floor(total / 3600000);
  return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}.${cs.toString().padStart(2, "0")}`;
}

/** numpad alignment: 2 bottom-center, 5 middle-center, 8 top-center. */
export function alignmentFor(position: SubtitleStyle["position"]): number {
  if (position === "top") return 8;
  if (position === "middle") return 5;
  return 2;
}

/** Escape text for a Dialogue line: braces are override blocks, newlines are \N. */
export function escapeAssText(text: string): string {
  return (text || "")
    .replace(/\r/g, "")
    .replace(/\n/g, "\\N")
    .replace(/[{}/]/g, (c) => ({ "{": "｛", "}": "｝", "/": "／" }[c] as string));
}

export interface AssMeta {
  /** Actual video resolution (used to derive the reference PlayRes). */
  width: number;
  height: number;
}

/**
 * Reference frame height for the ASS coordinate system.
 *
 * The preview box in the UI is 96 px tall and renders the font at
 * `fontSize / 2` CSS px.  That models a virtual 192 px-tall frame
 * (96 × 2).  Setting PlayResY to 192 makes the ASS-rendered text
 * match the preview proportions exactly — the ffmpeg `ass` filter
 * scales everything from this reference space to the actual output
 * resolution.
 */
const REF_H = 192;

export function generateAss(
  cues: SubtitleCue[],
  style: SubtitleStyle,
  meta: AssMeta,
): string {
  const alignment = alignmentFor(style.position);
  // Reference PlayRes matching the preview coordinate system.
  const refW = Math.round(meta.width * REF_H / meta.height);
  const header = [
    "[Script Info]",
    "; Generated by DirectorCam",
    "ScriptType: v4.00+",
    `PlayResX: ${refW}`,
    `PlayResY: ${REF_H}`,
    "WrapStyle: 0",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    [
      "Style: DCSub",
      style.fontFamily || "Arial",
      String(Math.round(style.fontSize)),
      toAssColor(style.color),
      toAssColor(style.color),
      toAssColor(style.outlineColor),
      "&H80000000",
      "0", "0", "0", "0",
      "100", "100", "0", "0",
      "1",
      String(Math.max(0, Math.round(style.outlineWidth))),
      "0",
      String(alignment),
      "40", "40",
      String(Math.max(0, Math.round(style.marginV))),
      "1",
    ].join(", "),
    "",
    "[Events]",
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
  ].join("\n");

  const events = cues
    .filter((c) => c.endMs > c.startMs && (c.text || "").trim())
    .map((c) =>
      `Dialogue: 0,${assTime(c.startMs)},${assTime(c.endMs)},DCSub,,0,0,0,,${escapeAssText(c.text.trim())}`,
    );

  return header + "\n" + events.join("\n") + "\n";
}
