/**
 * Perceptual hashing for the privacy-mask backtrace.
 *
 * The backtrace scans recorded frames (extracted by ffmpeg as small grayscale
 * raw frames) to find when the masked region's content — together with its
 * full-screen context — first appeared. Both signals are dHash (difference
 * hash) values compared by Hamming distance, which tolerates compression
 * noise, the cursor passing through, and a taskbar clock change while still
 * separating genuinely different pages.
 *
 * Search POSITIONS are generated by `regionSearchCandidates` (drawn box + a
 * local 3x3 offset grid + a coarse full-frame grid) so the first appearance
 * is found even when the content previously sat at a different spot (scrolled
 * page, moved window) — the export then cuts that pre-box window instead of
 * trying to track the content.
 *
 * This module is PURE: it operates on plain grayscale byte buffers, so it is
 * unit-testable and runs in both the renderer (reference sampling) and the
 * main process (frame scanning).
 */

import type { MaskRegion } from "../recording/edl";

export interface GrayFrame {
  /** Bytes of grayscale pixels, length = width * height. */
  data: Uint8Array;
  width: number;
  height: number;
}

export interface Hash64 {
  /** Low 32 bits. */
  lo: number;
  /** High 32 bits. */
  hi: number;
}

export interface RegionRef {
  /** Hash of the masked region's content. */
  region: Hash64;
  /** Hash of the full frame (page/window context). */
  frame: Hash64;
}

export interface FrameMatch {
  frameIndex: number;
  regionScore: number;
  frameScore: number;
  accepted: boolean;
}

/** Crop a normalized (0..1) rectangle and resample to size×size grayscale. */
export function cropResize(
  frame: GrayFrame,
  rect: { x: number; y: number; w: number; h: number },
  size: number,
): GrayFrame {
  const x0 = Math.max(0, Math.floor(rect.x * frame.width));
  const y0 = Math.max(0, Math.floor(rect.y * frame.height));
  const x1 = Math.min(frame.width, Math.max(x0 + 1, Math.ceil((rect.x + rect.w) * frame.width)));
  const y1 = Math.min(frame.height, Math.max(y0 + 1, Math.ceil((rect.y + rect.h) * frame.height)));
  const cw = x1 - x0;
  const ch = y1 - y0;
  const out = new Uint8Array(size * size);
  // Area-average resampling (box filter) — averages out text antialiasing and
  // single-pixel noise far better than nearest-neighbor.
  for (let oy = 0; oy < size; oy++) {
    const sy0 = y0 + Math.floor((oy * ch) / size);
    const sy1 = Math.max(sy0 + 1, y0 + Math.floor(((oy + 1) * ch) / size));
    for (let ox = 0; ox < size; ox++) {
      const sx0 = x0 + Math.floor((ox * cw) / size);
      const sx1 = Math.max(sx0 + 1, x0 + Math.floor(((ox + 1) * cw) / size));
      let sum = 0;
      let n = 0;
      for (let sy = sy0; sy < sy1; sy++) {
        let row = sy * frame.width;
        for (let sx = sx0; sx < sx1; sx++) {
          sum += frame.data[row + sx];
          n++;
        }
      }
      out[oy * size + ox] = n ? sum / n : 0;
    }
  }
  return { data: out, width: size, height: size };
}

/**
 * Candidate screen positions where the masked content could be visible, in
 * the same normalized space as the mask region: the exact drawn box, a 3x3
 * offset grid around it (content scrolled a box or two away), and a coarse
 * full-frame grid (the window that held the content was elsewhere earlier).
 *
 * `cropResize` clamps each candidate into the frame, so out-of-bounds offsets
 * simply scan the edge of the frame.
 */
export function regionSearchCandidates(region: MaskRegion): MaskRegion[] {
  const out: MaskRegion[] = [];
  const add = (r: MaskRegion): void => {
    if (r.w <= 0 || r.h <= 0 || !Number.isFinite(r.x) || !Number.isFinite(r.y)) return;
    const dup = out.some(
      (o) =>
        Math.abs(o.x - r.x) < 1e-6 && Math.abs(o.y - r.y) < 1e-6 &&
        Math.abs(o.w - r.w) < 1e-6 && Math.abs(o.h - r.h) < 1e-6,
    );
    if (!dup) out.push(r);
  };
  add(region);
  for (let dx = -1; dx <= 1; dx++) {
    for (let dy = -1; dy <= 1; dy++) {
      add({ x: region.x + dx * region.w, y: region.y + dy * region.h, w: region.w, h: region.h });
    }
  }
  for (let cx = 0; cx < 3; cx++) {
    for (let cy = 0; cy < 2; cy++) {
      add({ x: cx / 3, y: cy / 2, w: region.w, h: region.h });
    }
  }
  return out;
}

/**
 * dHash: average the frame into (size+1) x size cells, then each bit compares
 * a cell with its right neighbor (8x8 = 64 bits). Cell averaging matches what
 * a video downscaler does, so it survives compression ringing and single-pixel
 * noise (cursor) while page-level layout changes still flip many bits.
 */
export function dHash(frame: GrayFrame, size = 8): Hash64 {
  const cols = size + 1;
  const cw = frame.width / cols;
  const ch = frame.height / size;
  const cell = (cx: number, cy: number): number => {
    const x0 = Math.min(frame.width - 1, Math.floor(cx * cw));
    const x1 = Math.max(x0 + 1, Math.min(frame.width, Math.floor((cx + 1) * cw)));
    const y0 = Math.min(frame.height - 1, Math.floor(cy * ch));
    const y1 = Math.max(y0 + 1, Math.min(frame.height, Math.floor((cy + 1) * ch)));
    let sum = 0;
    let n = 0;
    for (let y = y0; y < y1; y++) {
      const row = y * frame.width;
      for (let x = x0; x < x1; x++) {
        sum += frame.data[row + x];
        n++;
      }
    }
    return n ? sum / n : 0;
  };
  let lo = 0;
  let hi = 0;
  let bit = 0;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      if (cell(x, y) > cell(x + 1, y)) {
        if (bit < 32) lo |= 1 << bit;
        else hi |= 1 << (bit - 32);
      }
      bit++;
    }
  }
  return { lo: lo >>> 0, hi: hi >>> 0 };
}

/** Hamming distance between two 64-bit hashes split into halves. */
export function hammingDistance(a: Hash64, b: Hash64): number {
  let d = 0;
  let x = (a.lo ^ b.lo) >>> 0;
  while (x) { d += x & 1; x >>>= 1; }
  x = (a.hi ^ b.hi) >>> 0;
  while (x) { d += x & 1; x >>>= 1; }
  return d;
}

/** Similarity in 0..1 (1 = identical hash). */
export function hashSimilarity(a: Hash64, b: Hash64): number {
  return 1 - hammingDistance(a, b) / 64;
}

export function hashToHex(h: Hash64): string {
  return (h.hi >>> 0).toString(16).padStart(8, "0") + (h.lo >>> 0).toString(16).padStart(8, "0");
}

export function hashFromHex(hex: string): Hash64 {
  const clean = (hex || "").replace(/[^0-9a-fA-F]/g, "").padEnd(16, "0").slice(0, 16);
  return {
    hi: parseInt(clean.slice(0, 8), 16) >>> 0,
    lo: parseInt(clean.slice(8), 16) >>> 0,
  };
}

export interface BacktraceThresholds {
  /** Minimum region similarity for the content signal (0..1). */
  region?: number;
  /** Minimum full-frame similarity for the context signal (0..1). */
  frame?: number;
}

export const DEFAULT_THRESHOLDS: Required<BacktraceThresholds> = {
  // The region holds the same text pixels, so it should score high; the frame
  // carries cursor/clock noise plus whatever else changed, so it runs looser.
  region: 0.86,
  frame: 0.78,
};

/**
 * One step of the backward scan: given per-frame hashes (chronological) and
 * the reference, find the FIRST (earliest) frame where both the region content
 * and the full-screen context match. Later frames implicitly match too (the
 * content is still on screen when the user presses the key), so the earliest
 * joint match is the moment the sensitive content appeared on this page.
 *
 * Returns null when no frame clears both thresholds — the caller falls back
 * to the grace window. `limit` bounds the accepted list (diagnostics only).
 */
export function findFirstJointMatch(
  frameHashes: Hash64[],
  regionHashes: Hash64[],
  ref: RegionRef,
  thresholds: BacktraceThresholds = {},
): { index: number; scores: FrameMatch[] } | null {
  const th = { ...DEFAULT_THRESHOLDS, ...thresholds };
  const scores: FrameMatch[] = [];
  for (let i = 0; i < frameHashes.length; i++) {
    const rs = hashSimilarity(regionHashes[i], ref.region);
    const fs = hashSimilarity(frameHashes[i], ref.frame);
    const ok = rs >= th.region && fs >= th.frame;
    scores.push({ frameIndex: i, regionScore: rs, frameScore: fs, accepted: ok });
    if (ok) return { index: i, scores };
  }
  return { index: -1, scores };
}

// ---------------------------------------------------------------------------
// Backtrace ladder (full matching pipeline over per-frame scores)
// ---------------------------------------------------------------------------

export interface FrameScores {
  /** similarity of the masked region's content */
  region: number;
  /** similarity of the region expanded to a local neighborhood (context 2) */
  neighborhood: number;
  /** similarity of the full frame (page/window context) */
  frame: number;
}

export type BacktraceMethod = "match" | "neighborhood" | "region" | "dynamic";

export interface DynamicEntranceOptions {
  /** Minimum region similarity to count as "content already partially there". */
  softRegion?: number;
  /** Minimum band crop inter-frame diff (0..255) to count as "content moving". */
  motionMin?: number;
  /** Maximum number of frames the entrance extension may walk back. */
  maxExtendFrames?: number;
}

/**
 * Dynamic-entrance extension of the backward trace. The masked content often
 * does not arrive already static: it slides in / fades / pops through several
 * positions and THEN settles, and only then does the user box it. The static
 * backtrace finds the first frame where the content LOOKS like the final
 * reference (i.e. after it settled) — so every dynamic-reveal frame between
 * the real first appearance and the settle frame is left to leak.
 *
 * Walking BACKWARD from that static match, keep extending while either
 *   - the region still shows a partial content match (soft threshold), or
 *   - the band area is still moving (inter-frame crop difference),
 * and stop at the first quiet frame (neither). The returned index is the
 * entrance start: export then cuts/mosaics [that -> draw-time] wholesale.
 */
export function extendBacktraceForDynamicEntrance(
  scores: FrameScores[],
  cropDiffs: number[],
  opts: DynamicEntranceOptions & { startIndex: number },
): number {
  const soft = opts.softRegion ?? 0.60;
  const motion = opts.motionMin ?? 14;
  const cap = opts.maxExtendFrames ?? 240;
  let i = opts.startIndex;
  let extended = 0;
  while (i > 0 && extended < cap) {
    i--;
    const partial = scores[i].region >= soft;
    const moving = cropDiffs[i] >= motion;
    if (!partial && !moving) { i++; break; }
    extended++;
  }
  return i;
}

/**
 * Four-step fallback ladder over the per-frame scores (chronological):
 *  1. region + full-frame context           -> "match"
 *  2. region + local neighborhood context   -> "neighborhood"
 *     (robust when other windows/animations drag the full-frame score down)
 *  3. region only, with a stricter threshold -> "region" (flag for review)
 *  4. nothing                               -> null (caller uses the grace window)
 * Returns the EARLIEST frame accepted by the highest ladder step that yields
 * any accept, plus its step method.
 */
export function resolveBacktraceStart(
  scores: FrameScores[],
  thresholds: BacktraceThresholds = {},
): { index: number; method: BacktraceMethod } | null {
  const th = { ...DEFAULT_THRESHOLDS, ...thresholds };
  const regionStrict = Math.min(0.96, th.region + 0.05);

  for (let i = 0; i < scores.length; i++) {
    if (scores[i].region >= th.region && scores[i].frame >= th.frame) {
      return { index: i, method: "match" };
    }
  }
  for (let i = 0; i < scores.length; i++) {
    if (scores[i].region >= th.region && scores[i].neighborhood >= th.frame) {
      return { index: i, method: "neighborhood" };
    }
  }
  for (let i = 0; i < scores.length; i++) {
    if (scores[i].region >= regionStrict) {
      return { index: i, method: "region" };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Export-time occurrence detection
// ---------------------------------------------------------------------------
//
// The masked content does NOT teleport around the screen: its screen position
// is determined by the page/window layout (it moves when the page scrolls or
// the window shifts). So detection searches a bounded band AROUND the drawn
// box — the relative spot where the layout can carry the content — instead of
// sweeping the whole frame randomly. Each candidate crop is compared twice:
//   1. dHash similarity  against the stored region fingerprint (recall),
//   2. normalized cross-correlation of the grayscale 16x16 crops (precision).
// The two together keep the comparison strong when the content reappears with
// slightly different noise/antialiasing.

export interface OccurrenceHit {
  /** Normalized rect (same space as MaskRegion) where the content matched. */
  rect: MaskRegion;
  /** Combined confidence in 0..1. */
  sim: number;
}

export interface OccurrenceSample {
  tMs: number;
  rect: MaskRegion;
  sim: number;
}

export interface OccurrenceRun {
  /** Recording-time window (ms) during which the content sat at `rect`. */
  t0: number;
  t1: number;
  rect: MaskRegion;
}

export interface DetectOptions {
  /** Minimum dHash similarity for a candidate (recall gate). */
  dHashMin?: number;
  /** Minimum cross-correlation (precision gate; null disables NCC). */
  nccMin?: number;
  /** 1 / stepDiv of the smaller template is the slide step (denser = slower). */
  stepDiv?: number;
  /** Horizontal band is +-bandX * box width around the drawn position. */
  bandX?: number;
  /** Vertical band is +-bandY * box height around the drawn position. */
  bandY?: number;
  /** Coarse whole-frame grid stride in scan pixels (safety net for far-off
   *  occurrences well outside the relative band; null disables it). */
  coarseStride?: number | null;
  /** Sub-grid refinement: after NMS, re-centered each hit with +-refinePx px
   *  shifts so the mosaic hugs the content instead of the grid step. */
  refinePx?: number;
  maxHits?: number;
}

export interface OccurrenceTimes {
  /** Max allowed gap (ms) between detection frames treated as the same run. */
  runGapMs?: number;
  /** Cells are quantized to 1/2^cellBits of the frame so runs merge by spot. */
  cellBits?: number;
  /** Cell distance tolerated for the same run. The sub-grid refine moves each
   *  hit +-refinePx px, i.e. bounces across adjacent cells between frames; a
   *  strict == would shatter one continuous occurrence into 1-2-frame runs
   *  that leave the rest of the presence unmosaicked. */
  cellTol?: number;
}

/** Decode a hex pixel dump (size*size bytes) into a grayscale buffer. */
export function decodeGrayPixels(hex: string, size: number): Uint8Array | null {
  const clean = (hex || "").replace(/[^0-9a-fA-F]/g, "");
  if (clean.length < size * size * 2) return null;
  const out = new Uint8Array(size * size);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

/** Encode a grayscale buffer (size*size bytes) as hex — the mirror of
 *  decodeGrayPixels, used to (re)build a scan-consistent template. */
export function encodeGrayPixels(g: GrayFrame): string {
  let out = "";
  for (let i = 0; i < g.data.length; i++) out += g.data[i].toString(16).padStart(2, "0");
  return out;
}

/** Build an occurrence-scan reference (region dHash + 16x16 grayscale hex)
 *  from ONE frame, so it matches the scan's own pipeline exactly. */
export function refFromFrame(frame: GrayFrame, region: MaskRegion): { refRegionHash: string; refPixels: string } {
  const crop = cropResize(frame, region, 16);
  return { refRegionHash: hashToHex(dHash(crop, 8)), refPixels: encodeGrayPixels(crop) };
}

/** Pearson correlation (0..1) of two equal-length grayscale buffers. */
export function normalizedCorrelation(a: Uint8Array, b: Uint8Array): number {
  const n = Math.min(a.length, b.length);
  if (n === 0) return 0;
  let ma = 0;
  let mb = 0;
  for (let i = 0; i < n; i++) { ma += a[i]; mb += b[i]; }
  ma /= n;
  mb /= n;
  let num = 0;
  let da = 0;
  let db = 0;
  for (let i = 0; i < n; i++) {
    const av = a[i] - ma;
    const bv = b[i] - mb;
    num += av * bv;
    da += av * av;
    db += bv * bv;
  }
  const den = Math.sqrt(da * db);
  if (den <= 0) return 0;
  return Math.max(0, Math.min(1, num / den));
}

function rectIoU(a: MaskRegion, b: MaskRegion): number {
  const ax0 = a.x, ay0 = a.y, ax1 = a.x + a.w, ay1 = a.y + a.h;
  const bx0 = b.x, by0 = b.y, bx1 = b.x + b.w, by1 = b.y + b.h;
  const ix0 = Math.max(ax0, bx0), iy0 = Math.max(ay0, by0);
  const ix1 = Math.min(ax1, bx1), iy1 = Math.min(ay1, by1);
  const iw = Math.max(0, ix1 - ix0), ih = Math.max(0, iy1 - iy0);
  const inter = iw * ih;
  const union = a.w * a.h + b.w * b.h - inter;
  return union > 0 ? inter / union : 0;
}

function nonMaximumSuppress(hits: OccurrenceHit[], iouTh = 0.5, max = 8): OccurrenceHit[] {
  const sorted = [...hits].sort((p, q) => q.sim - p.sim);
  const kept: OccurrenceHit[] = [];
  for (const h of sorted) {
    if (kept.some((k) => rectIoU(k.rect, h.rect) > iouTh)) continue;
    kept.push(h);
    if (kept.length >= max) break;
  }
  return kept;
}

function scoreCandidate(
  frame: GrayFrame,
  cand: MaskRegion,
  refHash: Hash64,
  p: Uint8Array | null,
  dHashMin: number,
  nccMin: number | null,
): number | null {
  const crop = cropResize(frame, cand, 16);
  const sim = hashSimilarity(dHash(crop), refHash);
  if (sim < dHashMin) return null;
  // Cross-correlation confirms texture matches; a zero-variance pair (e.g. the
  // reference itself was a solid uniform block, or the found spot is) carries
  // no NCC signal — the dHash of two flat crops is trivially 1, so instead gate
  // on mean brightness proximity: a solid bright block must not match a flat
  // background of a different level.
  if (p && nccMin !== null && (hasVariance(p) === false || hasVariance(crop.data) === false)) {
    if (Math.abs(meanOf(p) - meanOf(crop.data)) > 45) return null;
  } else if (p && nccMin !== null) {
    const ncc = normalizedCorrelation(p, crop.data);
    if (ncc < nccMin) return null;
    return 0.75 * sim + 0.25 * ncc;
  }
  return sim;
}

/**
 * Ungated match quality for the sub-pixel refine loop: the same landscape
 * scoreCandidate decides on, but continuous so refinement can climb toward the
 * true position. A flat-brightness mismatch is strongly rejected (like the
 * gate would), so a pure-flat crop cannot win over the real spot just because
 * a uniform reference hashes 1.0 against it.
 */
function candidateQuality(frame: GrayFrame, cand: MaskRegion, refHash: Hash64, p: Uint8Array | null): number {
  const crop = cropResize(frame, cand, 16);
  const sim = hashSimilarity(dHash(crop), refHash);
  if (p) {
    if (hasVariance(p) === false || hasVariance(crop.data) === false) {
      return Math.abs(meanOf(p) - meanOf(crop.data)) <= 45 ? sim : -Infinity;
    }
    return 0.75 * sim + 0.25 * normalizedCorrelation(p, crop.data);
  }
  return sim;
}

function hasVariance(a: Uint8Array): boolean {
  let min = 255;
  let max = 0;
  for (let i = 0; i < a.length; i++) {
    if (a[i] < min) min = a[i];
    if (a[i] > max) max = a[i];
  }
  return max - min > 0;
}

function meanOf(a: Uint8Array): number {
  let sum = 0;
  for (let i = 0; i < a.length; i++) sum += a[i];
  return a.length ? sum / a.length : 0;
}

function clampRect(r: MaskRegion, fw: number, fh: number): MaskRegion {
  const x = Math.max(0, Math.min(fw - r.w, r.x));
  const y = Math.max(0, Math.min(fh - r.h, r.y));
  return { x, y, w: r.w, h: r.h };
}

/**
 * Find every spot in `frame` where the masked content appears. The search is
 * primarily bounded to a relative band around the drawn box (the content
 * travels with the page/window layout, so its position is never random),
 * extended by a coarse whole-frame grid as a safety net for occurrences well
 * off that band. Candidates are gated by dHash similarity and confirmed by
 * normalized cross-correlation against the captured 16x16 template, then each
 * surviving hit is re-centered to sub-grid precision so the mosaic hugs the
 * content instead of sitting a half-step low/high.
 */
export function detectFrameOccurrences(
  frame: GrayFrame,
  region: MaskRegion,
  refHash: Hash64,
  refPixels?: string | null,
  opts: DetectOptions = {},
): OccurrenceHit[] {
  const dHashMin = opts.dHashMin ?? 0.82;
  const nccMin = opts.nccMin ?? 0.30;
  const stepDiv = opts.stepDiv ?? 3;
  const bandX = opts.bandX ?? 2.5;
  const bandY = opts.bandY ?? 3;
  const coarseStride = opts.coarseStride !== undefined ? opts.coarseStride : 40;
  const refinePx = opts.refinePx ?? 2;
  const p = decodeGrayPixels(refPixels || "", 16);

  const fw = frame.width;
  const fh = frame.height;
  const tw = Math.max(2, Math.round(region.w * fw));
  const th = Math.max(2, Math.round(region.h * fh));
  const step = Math.max(2, Math.round(Math.min(tw, th) / stepDiv));
  const bx0 = region.x - bandX * region.w;
  const by0 = region.y - bandY * region.h;
  const bx1 = region.x + (1 + bandX) * region.w;
  const by1 = region.y + (1 + bandY) * region.h;

  const candidates: { x: number; y: number }[] = [];
  const xs: number[] = [];
  for (let x = Math.max(0, Math.floor(bx0 * fw)); x + tw <= fw; x += step) {
    const rx = x / fw;
    if (rx > bx1) break;
    xs.push(x);
  }
  for (let y = Math.max(0, Math.floor(by0 * fh)); y + th <= fh; y += step) {
    const ry = y / fh;
    if (ry > by1) break;
    for (let i = 0; i < xs.length; i++) {
      candidates.push({ x: xs[i], y });
    }
  }
  // Coarse whole-frame net (keeps the total candidate count modest). Two phase
  // offsets (stride/2) in each axis make the effective cell a quarter of the
  // stride: without them a small occurrence whose whole crop box straddles the
  // gap between two coarse rows (no cell contains it) is invisible even though
  // a half-stride-away crop would hold it almost entirely.
  if (coarseStride && coarseStride > 0) {
    const phases = coarseStride >= 4 ? [0, Math.floor(coarseStride / 2)] : [0];
    for (const py of phases) {
      for (const px of phases) {
        for (let y = py; y + th <= fh; y += coarseStride) {
          for (let x = px; x + tw <= fw; x += coarseStride) {
            const insideBand = x >= Math.max(0, Math.floor(bx0 * fw)) && x + tw <= Math.min(fw, Math.ceil(bx1 * fw)) &&
              y >= Math.max(0, Math.floor(by0 * fh)) && y + th <= Math.min(fh, Math.ceil(by1 * fh));
            if (insideBand) continue; // already scanned densely
            candidates.push({ x, y });
          }
        }
      }
    }
  }

  // Screening pass: full gate with a LOOSENED dHash bar over every lattice
// position. The gate is applied a second time AFTER sub-pixel refinement —
// a lattice position a few px off the text scores just under the strict gate
// but its refined center is a bullseye, so the looser bar keeps those alive.
// (The precision side — NCC or the flat-vs-flat brightness gate — runs here
// too: a uniform reference hash trivially matches ANY flat background at
// dHash~1.0, and letting those flood the ranking hides the real hit.)
  const prePass: { x: number; y: number; sim: number }[] = [];
  for (let i = 0; i < candidates.length; i++) {
    const c = candidates[i];
    const sim = scoreCandidate(frame, { x: c.x / fw, y: c.y / fh, w: region.w, h: region.h }, refHash, p, dHashMin - 0.22, nccMin);
    if (sim !== null) prePass.push({ x: c.x, y: c.y, sim });
  }
  prePass.sort((a, b) => b.sim - a.sim);
  const top = prePass.slice(0, Math.max(6, (opts.maxHits ?? 8) * 4));
  if (top.length === 0) return [];

  // Sub-pixel re-center: search a window wide enough for the coarsest lattice
  // (band slide step or the coarse stride), first on a lattice stride then fine
  // around the best, and only THEN gate the refined score. Ranking uses the
  // full quality (dHash + NCC / brightness), because a uniform reference
  // scores 1.0 against any flat crop by dHash alone.
  const win = Math.max(refinePx, Math.ceil(Math.max(step, coarseStride && coarseStride > 0 ? coarseStride : 0) / 2));
  const lattice = Math.max(2, Math.round(win / 3));
  const hits: OccurrenceHit[] = [];
  for (const t of top) {
    let best: { x: number; y: number; sim: number } | null = null;
    for (let dy = -win; dy <= win; dy += lattice) {
      for (let dx = -win; dx <= win; dx += lattice) {
        if (dx === 0 && dy === 0) continue;
        const r = clampRect({ x: t.x + dx, y: t.y + dy, w: tw, h: th }, fw, fh);
        const q = candidateQuality(frame, { x: r.x / fw, y: r.y / fh, w: region.w, h: region.h }, refHash, p);
        if (!best || q > best.sim) best = { x: r.x, y: r.y, sim: q };
      }
    }
    if (!best) best = { x: t.x, y: t.y, sim: t.sim };
    for (let dy = -lattice; dy <= lattice; dy++) {
      for (let dx = -lattice; dx <= lattice; dx++) {
        if (dx === 0 && dy === 0) continue;
        const r = clampRect({ x: best.x + dx, y: best.y + dy, w: tw, h: th }, fw, fh);
        const q = candidateQuality(frame, { x: r.x / fw, y: r.y / fh, w: region.w, h: region.h }, refHash, p);
        if (q > best.sim) best = { x: r.x, y: r.y, sim: q };
      }
    }
    // Gate AFTER the refined position is known.
    const sim = scoreCandidate(frame, { x: best.x / fw, y: best.y / fh, w: region.w, h: region.h }, refHash, p, dHashMin, nccMin);
    if (sim !== null) {
      hits.push({ rect: { x: best.x / fw, y: best.y / fh, w: region.w, h: region.h }, sim });
    }
  }
  return nonMaximumSuppress(hits, 0.5, opts.maxHits ?? 8);
}

/**
 * Merge per-frame detection samples into time runs: consecutive samples on the
 * same quantized cell (and within `runGapMs`) form one occurrence run spanning
 * its first-to-last detection time. The run rect is the strongest match.
 */
export function mergeOccurrenceRuns(
  samples: OccurrenceSample[],
  opts: OccurrenceTimes = {},
): OccurrenceRun[] {
  const gap = opts.runGapMs ?? 600;
  const bits = opts.cellBits ?? 7;
  const cellTol = opts.cellTol ?? 1;
  const cellIndex = (v: number): number => Math.round(v * (1 << bits));
  const sorted = [...samples].sort((a, b) => a.tMs - b.tMs);
  const runs: OccurrenceRun[] = [];
  let cur: OccurrenceSample[] = [];
  for (const s of sorted) {
    let contiguous = false;
    if (cur.length) {
      const prev = cur[cur.length - 1];
      const xDist = Math.abs(cellIndex(prev.rect.x) - cellIndex(s.rect.x));
      const yDist = Math.abs(cellIndex(prev.rect.y) - cellIndex(s.rect.y));
      contiguous = s.tMs - prev.tMs <= gap && xDist <= cellTol && yDist <= cellTol;
    }
    if (contiguous) {
      cur.push(s);
    } else {
      if (cur.length) runs.push(finalizeRun(cur));
      cur = [s];
    }
  }
  if (cur.length) runs.push(finalizeRun(cur));
  return runs;

  function finalizeRun(group: OccurrenceSample[]): OccurrenceRun {
    const t0 = group[0].tMs;
    const t1 = group[group.length - 1].tMs;
    const strongest = group.reduce((a, b) => (b.sim > a.sim ? b : a), group[0]);
    return { t0, t1, rect: strongest.rect };
  }
}
