/**
 * Pro license keygen — the developer's offline signing tool. NEVER ship the
 * private key; only electron/license/publickey.ts is committed.
 *
 *   node scripts/license-keygen.mjs --init
 *     Creates .license-secret/easerec-pro.pem (gitignored) if absent and
 *     (re)writes electron/license/publickey.ts with the matching public key.
 *
 *   node scripts/license-keygen.mjs --count 300
 *     Signs `count` perpetual Pro codes into .license-codes/ as:
 *       - a .csv ledger (code, licenseNo, issuedDay) for your records
 *       - a .txt with one display-formatted code per line, ready to feed a
 *         card auto-delivery channel (爱发电 etc)
 *
 *   node scripts/license-keygen.mjs --count 1 --echo
 *     Prints a single code to stdout (support / replacement issuance).
 */

import { generateKeyPairSync, createPublicKey, randomBytes } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { makeProLicense, formatLicenseForDisplay } from "../electron/license/license-format.mjs";

const SECRET_DIR = ".license-secret";
const SECRET_FILE = path.join(SECRET_DIR, "easerec-pro.pem");
const CODES_DIR = ".license-codes";
const PUB_TS = path.join("electron", "license", "publickey.ts");

const args = process.argv.slice(2);
const flag = (name) => args.includes(name);
const num = (name, dflt) => {
  const i = args.indexOf(name);
  return i >= 0 ? Number(args[i + 1]) : dflt;
};

function createKeypair() {
  fs.mkdirSync(SECRET_DIR, { recursive: true });
  const { privateKey } = generateKeyPairSync("ed25519");
  fs.writeFileSync(SECRET_FILE, privateKey.export({ type: "pkcs8", format: "pem" }), { mode: 0o600 });
  console.log(`[keygen] new private key: ${SECRET_FILE} — BACK THIS UP, losing it ends all future issuance`);
}

function initCommand() {
  if (fs.existsSync(SECRET_FILE)) {
    console.log(`[keygen] private key already exists at ${SECRET_FILE} — reusing`);
  } else {
    createKeypair();
  }
  const pem = fs.readFileSync(SECRET_FILE, "utf8");
  const spki = createPublicKey(pem).export({ type: "spki", format: "der" });
  const ts = `// AUTO-GENERATED by scripts/license-keygen.mjs --init. Do not edit.\n`
    + `// Ed25519 public key (SPKI DER, hex) matching .license-secret/easerec-pro.pem.\n`
    + `export const LICENSE_PUBLIC_KEY_HEX = "${Buffer.from(spki).toString("hex")}";\n`;
  fs.writeFileSync(PUB_TS, ts);
  console.log(`[keygen] public key written to ${PUB_TS} (committed)`);
}

function issueCommand() {
  if (!fs.existsSync(SECRET_FILE)) {
    console.error(`[keygen] no private key at ${SECRET_FILE} — run with --init first`);
    process.exit(1);
  }
  const pem = fs.readFileSync(SECRET_FILE, "utf8");
  const count = Math.max(1, Math.min(10000, num("--count", 1)));
  fs.mkdirSync(CODES_DIR, { recursive: true });
  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const csvPath = path.join(CODES_DIR, `pro-batch-${stamp}.csv`);
  const txtPath = path.join(CODES_DIR, `pro-batch-${stamp}.txt`);
  const seen = new Set();
  const csvRows = ["code,licenseNo,issuedDay"];
  const lines = [];
  for (let i = 0; i < count; i++) {
    let lic;
    do {
      lic = makeProLicense(pem, { nonce: randomBytes(8) });
    } while (seen.has(lic.licenseNo));
    seen.add(lic.licenseNo);
    csvRows.push(`"${lic.display}","${lic.licenseNo}",${lic.issuedDay}`);
    lines.push(lic.display);
  }
  fs.writeFileSync(csvPath, "\ufeff" + csvRows.join("\n") + "\n", "utf8");
  fs.writeFileSync(txtPath, lines.join("\n") + "\n", "utf8");
  console.log(`[keygen] ${count} Pro codes -> ${csvPath} + ${txtPath}`);
  console.log(`[keygen] sample: ${lines[0]}`);
  if (flag("--echo")) lines.forEach((l) => console.log(l));
}

if (flag("--init")) initCommand();
else issueCommand();
