// AUTO-GENERATED by scripts/license-keygen.mjs --init. Do not edit.
// Ed25519 public key (SPKI DER, hex) matching .license-secret/easerec-pro.pem.
export const LICENSE_PUBLIC_KEY_HEX = "302a300506032b65700321007ea8498a358044e73b45e1fe03cf84541bab5419b36f730dec73b2bf79559074";
